# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia: 1.0.5
notifications:
  email: false
# uncomment the following lines to override the default test script
env:
    global:
    - PYTHON=conda
notifications:
  email: false
