# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia: 1.0.5
notifications:
  email: false
# uncomment the following lines to override the default test script
env:
    global:
    - PYTHON=conda
    matrix:
    - MPMATH=true
    - MPMATH=false
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.test("FEMTools"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("FEMTools")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("FEMTools")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
